import { createClient } from "@/lib/supabase/server";
import { NextResponse } from "next/server";

type RouteContext = { params: Promise<{ id: string }> };

// GET — assemble all saved vars into a .env file string (server-side only, never cached)
// Secret values are returned unmasked here because this endpoint is for WebContainer injection.
export async function GET(_req: Request, { params }: RouteContext) {
  const { id } = await params;
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { data, error } = await supabase
    .from("project_env_vars")
    .select("key, value")
    .eq("project_id", id)
    .eq("user_id", user.id)
    .order("key");

  if (error) return NextResponse.json({ error: error.message }, { status: 500 });

  const rows = data ?? [];
  if (rows.length === 0) {
    return new Response("", { headers: { "Content-Type": "text/plain", "Cache-Control": "no-store" } });
  }

  const dotenv = ["# Auto-generated by VibeCode — do not commit", ...rows.map((v) => `${v.key}=${v.value}`)].join(
    "\n"
  );

  return new Response(dotenv, {
    headers: { "Content-Type": "text/plain", "Cache-Control": "no-store" },
  });
}
